### ISSUE TITLE
TER statements are not changed on rechain/renumbering

### ISSUE THREAD

**Issue by JoaoRodrigues** [JoaoRodrigues/pdb-tools#14]
`pdb_chain` and `pdb_reres` should update the chain information on TER statements.

**Comment by joaomcteixeira** [comment]
`pdb_reres` already updates residues number in `TER` lines.
Residue renumbering will not take place in `TER` lines without chainID if a chain identification is provided in the script arguments, p.e. `-chain A`. If no -chain option is provided TER lines without chainID will be reres'ed accordingly to the preceding chain.

Considering the current behaviour of `reres`, I think it should not add any chain information to the `TER` line; it would be doing the function of `pdb_tidy`, isn't it?

**Comment by JoaoRodrigues** [comment]
This is because `pdb_reres` is doing two things ... I should revert it to the older version of renumbering the entire file. It would be more work but instead of:

`pdb_reres.py -chain A -resid 1 mystruct.pdb`

You could do:

```pdb_selchain.py -A mystruct.pdb | pdb_reres.py -1 > chainA.pdb
pdb_delchain.py -A mystruct.pdb > struct_noA.pdb
pdb_merge.py chainA.pdb struct_noA.pdb | pdb_sort.py -c | pdb_tidy.py > newStruct.pdb
```

It's cleaner, IMO.

**Comment by joaomcteixeira** [comment]
I understand and agree!

**Comment by JoaoRodrigues** [comment]
Addressed in version 2.
