### ISSUE TITLE
pdb_merge

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#15]
From the discussion in #13, `pdb_merge.py` should merge multiple PDB's chain information into a single file.  I understand that `TER` lines that do not exist in the original file should not be added (this is a job for `pdb_tidy.py`). But, should `pdb_merge.py` consider the original `TER` statements if they exist or only the `ATOM` and `HETATM` lines?

#discussion

**Comment by JoaoRodrigues** [comment]
That's a very good question. My original idea was to have each tool do one job. So, at the end, you should just pipe your result thought `pdb_tidy` to make sure things were OK. This avoids having other tools doing checks. What do you think?

**Comment by JoaoRodrigues** [comment]
Integrated in version 2. Kept the behaviour of reading `TER` statements (actually, reads everything) and it is up to the user to then pipe through `pdb_tidy` and `pdb_sort` to get a proper file.
