### ISSUE TITLE
Normalize options configuration

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#19]
Some scripts take options, though the way options are input is not equal across the repository. Some scripts take single letter option, others multiple letter options: p.e. `-a` and `-chain`.

Additionally, some scripts take options before the `input.pdb` other after (I am responsible for this discrepancies in `pdb_reres`).

I suggest options are identified by case sensitive single chars and those should precede the `input.pdb` string, which most likely was the original philosophy of pdb-tools.

**Comment by JoaoRodrigues** [comment]
Indeed. See my comment on #14.

**Comment by joaomcteixeira** [comment]
Correct,
I will try to implement that before we change options in the scripts (`pdb_reres` and `pdb_shiftres` for example).

**Comment by JoaoRodrigues** [comment]
Normalized all options across scripts in version 2.
