### ISSUE TITLE
pdb_reres

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#20]
Following our conversation on revert `pdb_reres` to its original version I want to ask,
`pdb_reres` restarts residue numbers from a given input number, the current version allows residue restart with three options: 1. for the entire PDB, 2. only of a given chain and 3. for each chain individually.

Instead of reverting `pdb_reres` to a single option, do you @JoaoRodrigues want to maintain at least the option to reres separately to each chain? In this way will avoid the need to split the PDB in multiple chain files go through a for loop (bash) to apply reres and then merge them again.

Do you agree with the following proposed USAGE?

```
Renumbers residues in a PDB file.

usage: python pdb_reres.py [-int] [-c] <pdb file>

options:
    -int (optional): integer from where residue renumber restarts, defaults to 1.
    -c (optional): sets reres to each chain separately.

examples:
    python pdb_reres.py 1CTF.pdb # reres from 1, sequentially in the entire PDB
    python pdb_reres.py 1CTF.pdb -50 # reres from 50, sequentially in the entire PDB
    python pdb_reres.py 1CTF.pdb -c # reres from 1 in each chain separately
    python pdb_reres.py 1CTF.pdb -50 -c # reres from 50 in each chain separately
```

**Comment by amjjbonvin** [comment]
Hi there

You might also want to take a look at pdb_shift.py 
It is to my opinion more useful often than pdb_reres, especially when you have missing segments in the coordinates file. pdb_reres would loose the gap while pdb_shift would preserve it. 
Or we need an option to pdb_reres to keep gaps

**Comment by joaomcteixeira** [comment]
Hello,

I had missed the `pdb_shiftres`. It's totally true. I don't know if makes sense to add an option to maintain gaps in `reres` if `shiftres` already does it. Considering everything said, maybe what we need is an option in `pdb_shiftres` to shift in every single chain without the need to manually specify all of them and then revert `pdb_reres` to its original functionality. In this way we could achieve all the functionalities we seek by piping both scripts.

**Comment by JoaoRodrigues** [comment]
Closing this. `pdb_reres` ignore gaps, `pdb_shiftres` keeps gaps. To renumber specific chains, extract it, renumber it, use `pdb_delchain` on the original and then `pdb_merge` to merge everything. `pdb_sort` and `pdb_tidy` at the end to make it nice.
