### ISSUE TITLE
pdb_sort behaviour

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#31]
**version 2**

`pdb_sort` accepts two options `-C` and `-R` and consequently `-CR`.

Currently:

`-R`: sorts by residues regardless of the chain identifier, this is, mixes all chains.
`-C`: sorts by chain identifier AND ALSO the residues inside the chain.

This makes `-CR` useless, as it is equal to `-C`.

I was not expecting `-C` to sort also the residues inside the chain and `-R` to mix all the chains, though I can understand the behavior of `-R` if `-CR` differs from `-C`.  Again, just want to confirm that is the expected behavior as I was expecting a completely different thing :-P

**Comment by joaomcteixeira** [comment]
Also, contrarily to other tools where ALL header lines are passed untouched, in `pdb_sort` only `HEADER` and `REMARK` are kept.

**Comment by JoaoRodrigues** [comment]
Fixed. It now stores the original chain ordering and sorts by that after sorting by residues if `-C` is not passed. Also sorts by insertion code, I'd forgotten that. Multi-model files are not supported. If it finds a MODEL/ENDMDL it exits with an error.
