### ISSUE TITLE
pdb_tidy behaviour

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#32]
**version 2**

- `pdb_tidy` does not remove previous `END` lines, resulting in doubled `END` statements.

```
ATOM     16  O   ASN A   1      21.581  38.297  -2.176  1.00  0.00           O  
TER      17      ASN A   1                                                      
END                                                                             
END    
```

Regardless the above mentioned bug, I agree with the current behavior of `pdb_tidy` (version2), namely the way it handles sequential chains and split chains with gaps and unsorted residues. @JoaoRodrigues could you run `pdb_tidy` on `tests/data/full_example.pdb` on `version2-unittest` branch to see if you agree with its behavior also?

**Comment by JoaoRodrigues** [comment]
I had an issue with how I found 'END' statements .. trying to match it after doing 'line.strip()' and waiting for a space anyway. Nice catch. Fixed.
