### ISSUE TITLE
pdb_selres check_input

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#33]
**version 2**

`pdb_selres` is not evaluating the input correctly when `-1:2:3:4` argument is given, according to:

`ERROR!! Residue range must be in 'a:z:s' where a and z are...`

Some `sys.exit(1)` are also missing when `sys.stderr.write()` which hinders the correct testing.

Tests have been written and currently output errors, _waiting for this correction_.

**Comment by JoaoRodrigues** [comment]
Fixed both, thanks!
