### ISSUE TITLE
pdb_delsc - one tool two jobs

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#35]
**verison 2**

Following the "one tool one job" rule, `pdb_delsc` deletes side chain atoms and allows for residue selection. This shouldn't be because of `pdb_selres` already selects residues.

**Comment by JoaoRodrigues** [comment]
Very true. I am removing it because we have `pdb_selatom` now, so this is the equivalent of doing `pdb_selatom -CA,C,N,O`. No need for redundancy.
