### ISSUE TITLE
Performance vs Memory Consumption

### ISSUE THREAD

**Issue by JoaoRodrigues** [JoaoRodrigues/pdb-tools#36]
I was doing some profiling to the code and realized the amount of memory used by each script is proportional to the number of lines the output contains. For example, using `pdb_merge` on one file will use x MBs but on four copies of that file it will be 4x. This is because of the `''.join()' statement, that unrolls the generator completely before writing:

```python
        sys.stdout.write(''.join(new_pdb))
        sys.stdout.flush()
```

I'm changing this at a cost of raw IO performance, by creating a temporary buffer and writing to file at specific intervals:

```python
        _buffer = []
        _buffer_size = 5000  # write N lines at a time
        for lineno, line in enumerate(new_pdb):
            if not (lineno % _buffer_size):
                sys.stdout.write(''.join(_buffer))
                _buffer = []
            _buffer.append(line)

        sys.stdout.write(''.join(_buffer))
        sys.stdout.flush()
```

Some testing with `pdb_merge` and `pdb_reres` indicate a slight loss of performance (x1.2-1.5 vs the original implementation) but memory consumption remains constant (peaks at 16-18 MBs).

**Comment by mtrellet** [comment]
Just to have an idea, how big is the memory consumption peak on your side? 
On OS + python 2.7.14, I reach about 100MB when merging 4 PDBs of a bit more than 100.000 lines (4kvb.pdb if you are curious). Peak is at 10MB with the solution you propose and a performance loss of about 1.5x.

The solution is very fine on my side but I won't apply it everywhere. Depending on the script, you end up using some scripts either 1) while iterating over a large number of files of "regular" size or 2) once on many (large) files at the same time. 
In the first case, the memory consumption is more than ok and I would favor performances, in the second case I'd definitely favor less memory usage. So we might want to implement that only on specific scripts that target multiple files as input.

**Comment by JoaoRodrigues** [comment]
>Just to have an idea, how big is the memory consumption peak on your side?
About the same. But it's proportional to the number of files parsed, so if you are merging a couple tens of files, or making an ensemble, of rather large files, you'll be hit with this. Also, it's a waste of using the generators as well :)

Is the performance hit that significant?

**Comment by JoaoRodrigues** [comment]
Changed everyone for consistency. Performance hit is minimal on my benchmarks. Will review if it becomes really slow...

**Comment by mtrellet** [comment]
Last tests made on my side showed only a slight performance drop, far to be significant, let's reopen if we get some comments on it indeed ;)
