### ISSUE TITLE
Addressing updating lines from one PDB to another

### ISSUE THREAD

**Issue by joaomcteixeira** [JoaoRodrigues/pdb-tools#37]
Following the discussion on #25 

>  If you develop pdb_selresname or pdb_selresid to perform actions on it, should there be a pdb_rplatom that takes atoms from pdb1 and replace those atom entries in pdb2?

I didn't explain myself properly, sorry. I didn't mean atom name (H, N, CA, etc), I meant atom number id. For example, PDB with chains A, B, C, atoms from 1 to 1000. One selects chain A, or `resname` or `resid`, performs some action on those selected lines (`pdb_whatever`), and then wants to paste the selected and altered lines back to the original PDB. Is there a tool on pdb-tools to perform that? To address this we could use atom ids (1, 2, 3, 4, ...) as an index to replace lines from one PDB (or flushed/piped lines) to another. That was my idea.

What do you think?

**Comment by JoaoRodrigues** [comment]
This is why I wrote `pdb_merge` and `pdb_sort`. The rationale would be:

```bash
# protein.pdb has chains A B and C
pdb_selchain -B protein.pdb | pdb_whatever > modified_B.pdb
pdb_delchain -B protein.pdb > protein_notB.pdb
pdb_merge protein_notB.pdb modified_B.pdb | pdb_sort
```

**Comment by joaomcteixeira** [comment]
I am aware, I was willing to avoid the creation of temporary PDB files. But, I accept this rationale for now :-P (jiji) An argument in favor of NOT doing what I suggested is to keep pdb-tools also as simple as possible, as defined in the mainlines.

So, we just need to address that this rationale can be applied to the relevant PDB _elements_: chain, resname, resid, etc found relevant. :+1:
